# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17df4018e3330ee0365f6df513bec79c320c38f2242159162618f9a0ac5cda0b2c5860904d6dfeeb82c71453457f674a73388891bab7f62fcfbd273e7b1d926c

test:
  secret_key_base: 73aaf7e0a864d7e9c640e33e2e984fa546927b1029cbbaa06c9de546fce03799b717776a3496b95894c6e5ba77a70a829d831519d957a850168c0d29500fa8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
